language: objective-c
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script: xctool -project Example/Example.xcodeproj -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test
