osx_image: xcode8.2
language: objective-c
podfile: Example/Podfile
before_script:
  - rvm get head || true # https://github.com/travis-ci/travis-ci/issues/6307
script: 
  - scan --device 'iPhone SE'
after_success:
  - bundle exec slather
  - bash <(curl -s https://codecov.io/bash)
