language: objective-c
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install cocoapods slather -N
podfile: Example/Podfile
script: 
  - make build
  - make test
after_success: slather
