language: objective-c
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install cocoapods
podfile: Example/Podfile
script: xctool -workspace Example/Example.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test
